### ISSUE TITLE
Smapp cannot run fine after reboot OS.

### ISSUE THREAD

**Issue by hryksbt** [spacemeshos/smapp#1410]
### Environment

* Smapp version: 1.0.9
* Ubuntu 22

### Describe the bug

Smap cannot run.

### Steps to reproduce

1.  Reboot OS.
2.  Start Smapp.

### Expected behavior

Smapp must run fine.

### Actual behavior

Network cannot establish.Remain PoST creation cannot complete.
I attache 2 screenshots.
![スクリーンショット 2023-07-30 17 11 58](https://github.com/spacemeshos/smapp/assets/2483747/37292254-78a7-4722-b93b-1a733e5cbb7d)
![スクリーンショット 2023-07-30 17 11 36](https://github.com/spacemeshos/smapp/assets/2483747/b699c5c5-114f-4403-8404-e15577987faf)

Attach screenshots or GIF’s of what’s going on if it makes the issue more illustrative.

### Logs

Attach `log.txt.zip`

**Comment by hryksbt** [comment]
There are same issue in 2 nodes.
Node A: Solved updating from 1.0.7 to 1.0.9.
Node B: Not solved updating from 1.0.7 to 1.0.9. Solved uninstall using `apt-get` command then install `dpkg` command.
Please check then fix it.

**Comment by hryksbt** [comment]
[log2.txt.zip](https://github.com/spacemeshos/smapp/files/12209231/log2.txt.zip)
I face same issue again. But this can't be solved by reinstall operation.
Please check log and tell me hoe to solve.

**Comment by brusherru** [comment]
Thanks for the report!

My summary from the logs:

1. Seems like for some reason there were running more than one instance of the Node at a time.
   Pay attention to these lines:
   ```
    2023-07-21T21:01:45.172+0900	ERROR	00000.defaultLogger	app failed to clean up in time	{"name": ""}
    2023-07-21T21:07:04.474+0900	INFO	00000.defaultLogger	App version: v1.0.3. Git: e91d735 - e91d7352d941718979438d9e37bfed9533008211 . Go Version: go1.19.11. OS: linux-amd64 
    2023-07-21T21:07:04.474+0900	INFO	00000.defaultLogger	Welcome to Spacemesh. Spacemesh full node is starting...
    2023-07-21T21:07:04.474+0900	INFO	00000.defaultLogger	Looking for identity file at `/media/user/4TB/SM/key.bin`
    2023-07-21T21:08:20.434+0900	INFO	00000.defaultLogger	App version: v1.0.3. Git: e91d735 - e91d7352d941718979438d9e37bfed9533008211 . Go Version: go1.19.11. OS: linux-amd64 
    2023-07-21T21:08:20.434+0900	INFO	00000.defaultLogger	Welcome to Spacemesh. Spacemesh full node is starting...
    2023-07-21T21:08:20.434+0900	INFO	00000.defaultLogger	Looking for identity file at `/media/user/4TB/SM/key.bin`
    2023-07-21T21:12:13.907+0900	INFO	00000.defaultLogger	App version: v1.0.3. Git: e91d735 - e91d7352d941718979438d9e37bfed9533008211 . Go Version: go1.19.11. OS: linux-amd64 
    2023-07-21T21:12:13.907+0900	INFO	00000.defaultLogger	Welcome to Spacemesh. Spacemesh full node is starting...
    2023-07-21T21:12:13.907+0900	INFO	00000.defaultLogger	Looking for identity file at `/media/user/4TB/SM/key.bin`
    2023-07-21T21:33:29.762+0900	INFO	00000.defaultLogger	App version: v1.0.3. Git: e91d735 - e91d7352d941718979438d9e37bfed9533008211 . Go Version: go1.19.11. OS: linux-amd64 
    2023-07-21T21:33:29.762+0900	INFO	00000.defaultLogger	Welcome to Spacemesh. Spacemesh full node is starting...
    2023-07-21T21:33:29.762+0900	INFO	00000.defaultLogger	Looking for identity file at `/media/user/4TB/SM/key.bin`
   ```
   and also latest lines of the log:
   ```
    2023-07-30T21:32:30.580+0900	ERROR	00000.defaultLogger	app failed to clean up in time	{"name": ""}
    2023-07-30T21:37:40.365+0900	INFO	00000.defaultLogger	App version: v1.0.6. Git: e4b88b8 - e4b88b8ae8b8c634b05c6cc5786ae4fa5cec4d46 . Go Version: go1.19.11. OS: linux-amd64 
    2023-07-30T21:37:40.365+0900	INFO	00000.defaultLogger	Welcome to Spacemesh. Spacemesh full node is starting...
    2023-07-30T21:37:40.365+0900	INFO	00000.defaultLogger	Looking for identity file at `/media/user/4TB/SM/key.bin`
    2023-07-30T21:43:54.205+0900	FATAL	00000.defaultLogger	failed to get exclusive file lock: only one spacemesh instance should be running (locking file /tmp/spacemesh.lock)	{"name": ""}
    2023-07-30T21:46:01.710+0900	FATAL	00000.defaultLogger	failed to get exclusive file lock: only one spacemesh instance should be running (locking file /tmp/spacemesh.lock)	{"name": ""}
    2023-07-30T21:46:07.859+0900	FATAL	00000.defaultLogger	failed to get exclusive file lock: only one spacemesh instance should be running (locking file /tmp/spacemesh.lock)	{"name": ""}
    2023-07-30T21:47:06.403+0900	FATAL	00000.defaultLogger	failed to get exclusive file lock: only one spacemesh instance should be running (locking file /tmp/spacemesh.lock)	{"name": ""}
    2023-07-30T21:47:09.896+0900	FATAL	00000.defaultLogger	failed to get exclusive file lock: only one spacemesh instance should be running (locking file /tmp/spacemesh.lock)	{"name": ""}
   ```

2. And probably it leads `atxBuilder` to crash sometime (there are two cases) with panic (one of the instances?):
    ```
	2023-07-19T13:35:50.572+0900	INFO	7113c.post	initialization: completed	{"node_id": "7113cf9b0fcb1ad32b13cd4d72b57caca5bab2b28d57e78948bab10798a4ad49", "module": "post", "fileIndex": 233, "numLabelsWritten": 134217728}
	2023-07-19T13:35:50.630+0900	ERROR	7113c.post	post setup session failed	{"node_id": "7113cf9b0fcb1ad32b13cd4d72b57caca5bab2b28d57e78948bab10798a4ad49", "module": "post", "errmsg": "open /media/user/4TB/SM/postdata_234.bin: input/output error", "name": "post"}
	2023-07-19T13:35:50.630+0900	ERROR	7113c.atxBuilder	Fatal: goroutine panicked. Stacktrace: goroutine 128 [running]:
	runtime/debug.Stack()
		/opt/hostedtoolcache/go/1.19.11/x64/src/runtime/debug/stack.go:24 +0x65
	github.com/spacemeshos/go-spacemesh/log.Log.Panic({0xc0001c21c0?, {0x1880c9b?, 0xc00108e100?}}, {0x19dbacc, 0x19}, {0xc0004417f0, 0x1, 0x1})
		/home/runner/work/go-spacemesh/go-spacemesh/log/zap.go:46 +0xd7
	github.com/spacemeshos/go-spacemesh/activation.(*Builder).StartSmeshing.func1()
		/home/runner/work/go-spacemesh/go-spacemesh/activation/activation.go:209 +0x1e7
	golang.org/x/sync/errgroup.(*Group).Go.func1()
		/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64
	created by golang.org/x/sync/errgroup.(*Group).Go
		/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5
		{"node_id": "7113cf9b0fcb1ad32b13cd4d72b57caca5bab2b28d57e78948bab10798a4ad49", "module": "atxBuilder"}
	2023-07-19T13:35:50.630+0900	PANIC	7113c.atxBuilder	initialization failed: open /media/user/4TB/SM/postdata_234.bin: input/output error	{"node_id": "7113cf9b0fcb1ad32b13cd4d72b57caca5bab2b28d57e78948bab10798a4ad49", "module": "atxBuilder"}
	panic: initialization failed: open /media/user/4TB/SM/postdata_234.bin: input/output error

	goroutine 128 [running]:
	go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x0?, {0x0?, 0x1?, 0x0?})
		/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
	go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0005f4340, {0x0, 0x0, 0x0})
		/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
	go.uber.org/zap.(*SugaredLogger).log(0xc000761d40, 0x4, {0x19dbacc?, 0x0?}, {0xc0004417f0?, 0x2?, 0x2?}, panic: initialization failed: open /media/user/4TB/SM/postdata_234.bin: input/output error

	goroutine 128 [running]:
	go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x0?, {0x0?, 0x1?, 0x0?})
		/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
	go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0005f4340, {0x0, 0x0, 0x0})
		/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
	go.uber.org/zap.(*SugaredLogger).log(0xc000761d40, 0x4, {0x19dbacc?, 0x0?}, {0xc0004417f0?, 0x2?, 0x2?}, {0x0, 0x0, 0x0})
		/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:295 +0xee
	go.uber.org/zap.(*SugaredLogger).Panicf(...)
		/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:189
	github.com/spacemeshos/go-spacemesh/log.Log.Panic({0xc0001c21c0?, {0x1880c9b?, 0xc00108e100?}}, {0x19dbacc, 0x19}, {0xc0004417f0, 0x1, 0x1})
		/home/runner/work/go-spacemesh/go-spacemesh/log/zap.go:47 +0x1fa
	github.com/spacemeshos/go-spacemesh/activation.(*Builder).StartSmeshing.func1()
		/home/runner/work/go-spacemesh/go-spacemesh/activation/activation.go:209 +0x1e7
	golang.org/x/sync/errgroup.(*Group).Go.func1()
		/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64
	created by golang.org/x/sync/errgroup.(*Group).Go
		/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5
	{0x0, 0x0, 0x0})
		/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:295 +0xee
	go.uber.org/zap.(*SugaredLogger).Panicf(...)
		/home/runner/go/pkg/mod/go.uber.org/zap@v1.24.0/sugar.go:189
	github.com/spacemeshos/go-spacemesh/log.Log.Panic({0xc0001c21c0?, {0x1880c9b?, 0xc00108e100?}}, {0x19dbacc, 0x19}, {0xc0004417f0, 0x1, 0x1})
		/home/runner/work/go-spacemesh/go-spacemesh/log/zap.go:47 +0x1fa
	github.com/spacemeshos/go-spacemesh/activation.(*Builder).StartSmeshing.func1()
		/home/runner/work/go-spacemesh/go-spacemesh/activation/activation.go:209 +0x1e7
	golang.org/x/sync/errgroup.(*Group).Go.func1()
		/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64
	created by golang.org/x/sync/errgroup.(*Group).Go
		/home/runner/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5
	2023-07-19T16:00:26.158+0900	INFO	00000.defaultLogger	Looking for identity file at `/media/user/4TB/SM/key.bin`
	2023-07-19T16:00:26.159+0900	INFO	00000.defaultLogger	Loaded existing identity; public key: 7113cf9b0fcb1ad32b13cd4d72b57caca5bab2b28d57e78948bab10798a4ad49
    ```

**Comment by yxz215** [comment]
this is because U ploting used GPU,then when U use cpu POST must change 0->4294967295
![image](https://github.com/spacemeshos/smapp/assets/118148749/4fc14d1f-2864-4e0c-b649-b5b0064a6eaf)

**Comment by hryksbt** [comment]
@yxz215 What should I do? Please let me know details. Thanks,

**Comment by hryksbt** [comment]
@brusherru I think Smapp is not written in logout or shutdown script of Ubuntu. So When we reboot OS without quit Smapp operation, this error might be occurred.
Please check it.

**Comment by yxz215** [comment]
@hryksbt open here
![image](https://github.com/spacemeshos/smapp/assets/118148749/118fb042-698f-4c1a-b002-124fcbb6dced)
find node-config.7c8cef2b json file ,change the  smeshing-opts-provider ,restart smapp

**Comment by hunjixin** [comment]
unable to sync after restart

**Comment by hryksbt** [comment]
@yxz215 
Thanks for your reply.
Could you tell me detail?

There is 

`"smeshing-opts-provider": 0,`

.

This should be 

`"smeshing-opts-provider": restart smapp,`

Is this correct?

**Comment by hryksbt** [comment]
> this is because U ploting used GPU,then when U use cpu POST must change 0->4294967295 ![image](https://user-images.githubusercontent.com/118148749/257111071-4fc14d1f-2864-4e0c-b649-b5b0064a6eaf.png)

I'm uging GPU.

**Comment by brusherru** [comment]
I believe this issue is not actual anymore :)
If I'm wrong — feel free to open a new issue, attach all details, and put a link to this issue.

**Comment by brusherru** [comment]
A couple of last words:

> I think Smapp is not written in logout or shutdown script of Ubuntu. So When we reboot OS without quit Smapp operation, this error might be occurred.

Actually, Smapp has nothing to do with it and OS should just close Smapp in this case.
Smapp, like any other application, does not have control over OS operations. So if it is smeshing (prompts to close) then it may delay rebooting (to give you a chance to select an option), pause rebooting, or just kill an app — it depends on OS.
