### ISSUE TITLE
App Doesnt close properly

### ISSUE THREAD

**Issue by antonlerner** [spacemeshos/smapp#865]
### Environment

* Smapp version: 0.xx.x | develop
* Node version: v0.x.xx 
* OS: Windows 10 | macOS High Sierra (10.13) | Ubuntu 20.04

### Describe the bug

Started app, white screen appeared, when tried to close it an error popped out:
Unhandled Promise Rejection
TypeError: Cannot read property 'stopNode' of undefined
    at /Applications/Spacemesh.app/Contents/Resources/app.asar/desktop/main.prod.js:20:188085
    at p (/Applications/Spacemesh.app/Contents/Resources/app.asar/desktop/main.prod.js:37:880047)
    at Generator._invoke (/Applications/Spacemesh.app/Contents/Resources/app.asar/desktop/main.prod.js:37:879835)
    at Generator.next (/Applications/Spacemesh.app/Contents/Resources/app.asar/desktop/main.prod.js:37:880472)
    at Nn (/Applications/Spacemesh.app/Contents/Resources/app.asar/desktop/main.prod.js:20:185296)
    at o (/Applications/Spacemesh.app/Contents/Resources/app.asar/desktop/main.prod.js:20:185500)

### Expected behavior

App should close

### Actual behavior
I can't close the app

Attach screenshots or GIF’s of what’s going on if it makes the issue more illustrative.

### Logs

Attach `app-logs.txt` and `spacemesh-log.txt`

If you can find out the part of the logs that relates to the problem, attach them or paste in code-block.

### How to fix 

If you have an idea of how the bug can be fixed, provide a short description.

**Comment by avive** [comment]
@antonlerner can you please repro with current devnet and smapp release v0.2.3 - I haven't seen this dialog box for a long time...

**Comment by oriya** [comment]
@brusherru I am guessing this is something we can close?

**Comment by maparr** [comment]
the issue is not relevant anymore.
